### ISSUE TITLE
Minor bug in youbot_oodl concerning visualization in rviz

### ISSUE THREAD

**Issue by mfaessle** [youbot/youbot-ros-pkg#18]
There is a minor bug in the youbot_oodl which I came across recently.

In the file "youbot_oodl / src / YouBotOODLWrapper.cpp" lines 797 - 803 currently are:

/*
 Yet another hack to make the published values compatible with the URDF description.
 We actually flipp the directions of the wheel on the right side such that the standard ROS controllers
 (e.g. for PR2) can be used for the youBot
*/
        baseJointStateMessage.position[2] = -baseJointStateMessage.position[2];
        baseJointStateMessage.position[4] = -baseJointStateMessage.position[4];

These indexes are wrong, they should be 0 and 2 instead of 2 and 4 so then the wheel turn correctly in rviz.

**Comment by frederikhegger** [comment]
Can you just send us a pull request? We will then merge it into the repository.

Thank you very much.

Best Regards,
Frederik hegger

**Comment by frederikhegger** [comment]
Pull request has been sent and merged. Thank you.
