### ISSUE TITLE
error with build on 12.04 concerning libopencv2.3-dev

### ISSUE THREAD

**Issue by carson** [youbot/youbot-ros-pkg#20]
I am trying to update the youbot-ros-pkg files on my custom rolled kuka youbot system. Following the instructions in the readme I am able to proceed until the following step:

youbot@kukaros1:~/ros_stacks/youbot-ros-pkg$ ./repository.debs
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package libopencv2.3-dev
E: Couldn't find any package by regex 'libopencv2.3-dev'

There do not seem to be packages for libopencv2.3-dev available on 12.04. We are using ROS fuerte.

**Comment by frederikhegger** [comment]
Dear Mr. Reynolds,
for Ubuntu 12.04 change the package name from "libopencv2.3-dev" to 
"libopencv-dev".

Best regards,
Frederik Hegger

**Comment by carson** [comment]
I'll try it out. Should the dependencies be modified to look for this by default?

**Comment by frederikhegger** [comment]
This issue has been addressed in the new repository: https://github.com/youbot/youbot_driver_ros_interface
